# Fetching the latest node image on alpine linux
FROM node:21.1.0 AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /automation-tool-frontend

# Installing dependencies
COPY ./package.json /automation-tool-frontend
RUN yarn install

# Copying all the files in our project
COPY . .

EXPOSE 3000

# Starting our application
CMD yarn start
