version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/automation-tool-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
