FROM node:21.1.0-alpine3.17 

ENV TERM xterm

RUN apk update && \
    apk add --no-cache build-base python3 py-pip && \
    pip3 --no-cache-dir install awscli && \
    rm -rf /var/cache/apk/*
RUN node -v